"""empty message

Revision ID: 843e15c69592
Revises: d135d38d115a
Create Date: 2020-09-16 01:34:59.388305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843e15c69592'
down_revision = 'd135d38d115a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
